### PR TITLE
fix: guarantee order of load events

### LINKED ISSUE #21: loadstart sometimes doesn't fire until the load is complete
include-fragment fires its events on a 0-delay timer. At least in Safari, this sometimes results in events not firing until after the load has already completed. I believe this is happening in the case where the load is served from the browser's cache; in that case the load completes so quickly that the timer for firing `loadstart` hasn't run yet.

### PR DESCRIPTION
**Pull request by keithamus**
Fixes #21

This refactors `fire` to return a Promise, so that we can determine when an event has been fired (as we're not firing event synchronously).

The test is pretty contrived and implementation dependant, but it red-greens consistently and race condition tests are hard to otherwise verify :shrug:

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -161,21 +162,15 @@ export default class IncludeFragmentElement extends HTMLElement {
         if (!isWildcard(this.accept) && (!ct || !ct.includes(this.accept ? this.accept : 'text/html'))) {
           throw new Error(`Failed to load resource: expected ${this.accept || 'text/html'} but was ${ct}`)
         }
-        return response
+        return response.text()
+      })
+      .then(data => {
+        fire('load', this).then(() => fire('loadend', this))
+        return Promise.resolve(data)
```
Comment (manuelpuyol) [inline src/index.ts:169]: why are we resolving `data` here? shouldn't we resolve the `fire` promise?

File: src/index.ts [hunk 2]
```diff
@@ -161,21 +163,27 @@ export default class IncludeFragmentElement extends HTMLElement {
         if (!isWildcard(this.accept) && (!ct || !ct.includes(this.accept ? this.accept : 'text/html'))) {
           throw new Error(`Failed to load resource: expected ${this.accept || 'text/html'} but was ${ct}`)
         }
-        return response
+        return response.text()
+      })
+      .then(data => {
+        // Dispatch `load` and `loadend` async to allow
+        // the `load()` promise to resolve _before_ these
```
Comment (manuelpuyol) [inline src/index.ts:170]:
```suggestion
        // the `loadstart()` promise to resolve _before_ these
```

If I'm understanding this correclty, shouldn't it be `loadstart` here?

Comment (keithamus) [reply src/index.ts:170]: This references the `load()` function. It is saying that the promise returned by the `load()` function should resolve before the `load`/`loadend` events are dispatched.

**Review by manuelpuyol — APPROVED** [review]

File: src/index.ts [hunk 3]
```diff
@@ -21,10 +21,9 @@ const observer = new IntersectionObserver(entries => {
...
 
 
-function fire(name: string, target: Element) {
-  setTimeout(function () {
-    target.dispatchEvent(new Event(name))
-  }, 0)
+// Functional stand in for the W3 spec "queue a task" paradigm
+function task(): Promise<void> {
+  return new Promise(resolve => setTimeout(resolve, 0))
 }
```
Comment (koddsson) [inline src/index.ts:27]: This is a lot cleaner!

File: src/index.ts [hunk 4]
```diff
@@ -148,9 +147,12 @@ export default class IncludeFragmentElement extends HTMLElement {
 
   load(): Promise<string> {
     observer.unobserve(this)
-    return Promise.resolve()
+    // We mimic the same event order as <img>, including the spec
+    // which states events must be dispatched after "queue a task".
+    // https://www.w3.org/TR/html52/semantics-embedded-content.html#the-img-element
+    return task()
```
Comment (koddsson) [inline src/index.ts:153]: This is really clear now.

File: test/test.js [hunk 5]
```diff
@@ -426,6 +426,39 @@ suite('include-fragment-element', function() {
...
+    elem.src = '/hello'
+
+    // Emulate some kind of timer clamping
+    const originalSetTimeout = window.setTimeout
+    let i = 60
+    window.setTimeout = (fn, ms, ...rest) => originalSetTimeout.call(window, fn, ms + (i -= 20), ...rest)
+
+    document.body.appendChild(elem)
+    return Promise.all(events).then(() => {
+      window.setTimeout = originalSetTimeout
```
Comment (koddsson) [inline test/test.js:456]: Can we move the timer clamping emulation and restoration into `before` and `after` hooks so that we don't end up with an emulated `setTimeout` if the tests fail?

**Review by koddsson — APPROVED** [review]
This is great!
